---
title: "How WEIRD-biased is CHILDES' data on children's linguistic input"
shorttitle        : "Verbal input among the Tsimane'"

author: 
  - name          : "Camila Scaff*"
    affiliation   : "1,2"
  - name          : "Georgia Loukatou*"
    affiliation   : "2"
  - name          : "Alejandrina Cristia"
    affiliation   : "2"
  - name          : "Naomi Havron"
    affiliation   : "3"
    
affiliation:
  - id: "1"
    institution: University of Zurich, Institute of Evolutionary Medicine (IEM), Switzerland
  - id: "2"
    institution: PSL University, Laboratoire de Sciences Cognitives et de Psycholinguistique (ENS, EHESS, CNRS, DEC), France
  - id: "3"
    institution: Haifa Univerity, Israel



  # - code: "2"
  #   address: ENS, EHESS, CNRS, PSL University, Laboratoire de Sciences Cognitives et de Psycholinguistique, Département d études cognitives, 29 rue d ulm, Paris, 75005, France

   



# corresp_author_name:  "ANON"
# corresp_author_email: "ANON"

abstract: |
  Child development studies are heavily biased towards WEIRD (Western, Educated, Industrialized, Rich and Democratic) populations. First, this paper situates the acronym in children's language development research, showing that only some of these dimensions may matter for the description of children's language input. Additional dimensions relevant for describing children's language input are the language(s) used and the child's family structure. Next, a descriptive analysis of 147 corpora from the major archive of child-centered language, CHILDES, revealed that naturalistic speech samples in CHILDES are markedly varied in terms of languages and countries. However, they are biased in terms of education, urbanization, wealth, and family structure, in terms of both the countries represented, and the samples gathered within these countries. 



## Remove this if not required
funding: |
  AC acknowledges financial and institutional support from Agence Nationale de la Recherche (ANR-16-DATA-0004 ACLEW, ANR-17-EURE-0017, ANR-14-CE30-0003 MechELex); the J. S. McDonnell Foundation Understanding Human Cognition Scholar Award; and the European Research Council (ERC) under the European Union’s Horizon 2020 research and innovation programme (ExELang, Grant agreement No. 101001095). GL acknowledges financial support from Fondation Fyssen.




## Remove this if not required
acknowledgements: |
  We are grateful to Lara Oliel and Clara Daoud for help entering corpus-level data; Sara Pisani for organizing communication with corpus curators; Brian MacWhinney for support and encouragement when retrieving information from corpus curators. We particularly want to thank the literally hundreds of researchers who contributed data to CHILDES, without which this project would be unthinkable; and the 103 curators who replied to our request.

# ac2cs shall we add their names? Do we have permission for that?


keywords          : "childes, verbal input, infant-directed speech, language, weird"
wordcount         : "8,300 words"


bibliography      : ["childes.bib"]

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---





```{r setup, include=FALSE}
#Sys.setlocale("LC_CTYPE", "en_US_POSIX.UTF-8")
#Sys.setlocale("LANG", "en_US_POSIX.UTF-8")
Sys.setlocale(category = "LC_ALL", locale = "en_SE.utf8")

knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE)
library("papaja")
library(psych)
library(car)
library(ggplot2)
library(scales)
library(gridExtra)
library(lme4)
library(ggpubr)
library(lmerTest)

library(knitr)
options(digits=1)
library(kableExtra)
library(dplyr)

library(magick)

library(effects)
library(gvlma)
library(influence.ME)
library("wesanderson")
library(introdataviz)
#devtools::install_github("psyteachr/introdataviz")
#library(ggalt)
library(Hmisc)
```

<!--There is a growing awareness among child development researchers, particularly those working on language acquisition, that the populations we sample are biased towards WEIRD (Western, Educated, Industrial, Rich, Democratic) populations. In this paper, we measure the width and depth of coverage in a major archive representing child-centered recordings, CHILDES (MacWhinney, 2000). CHILDES was founded in 1984, and contains corpora that go back as far as the beginning of the 20th century, all open access. As such, CHILDES has been not only a source of data hundreds of researchers of child language and beyond have openly accessed and used for their research, it has also been an early harbinger of the open science movement and the value of cumulative science. CHILDES’s value thus goes beyond its contribution to child-language acquisition research.  To pose the question within its proper context, we first introduce the acronym, and spotlight the fact that the acronym WEIRD represents a cluster of properties at the crossing of multiple dimensions. Based on previous work, we argue that only some of these dimensions are relevant for the description of children's language input, that is: how much speech is addressed to children, by whom, and with what qualitative features. In addition to WEIRD, we argue that other factors seem especially pertinent when discussing biases in sampling in language development, including an over-representation of children learning a small number of languages, typically monolingually, and while being cared for by their mother. -->

## WEIRD: Uses and limitations of the acronym
<!--In 2010 Henrich et al. brought to the forefront the concept of WEIRD people,  In psychological research, they claimed, we test mostly WEIRD people, but the great majority of people in the world today are not WEIRD. The bias towards sampling WEIRD people may stem from the fact that most scientists are WEIRD, leading convenience samples to be WEIRD as well. Moreover, scientists before may have thought that the questions they asked, and results they obtained, were so fundamental to human cognition that they should not vary across cultures, making it pointless to test varied populations. However, the results summarized in Heinrich et al. (2010) revealed that people of different backgrounds in fact did vary in their performance in psychological studies previously thought to reflect "universal" traits.--> 

There is a bias towards sampling WEIRD participants in psychological studies [@henrich2010], that is, individuals coming from Western, Educated, Industrialized, Rich and Democratic environments. The same bias exists in developmental research (Nielsen et al., 2017; Moriguchi, 2021; for child-centered recordings, see Cychosz & Cristia, 2022), and although a meta-analysis of examining bias in infant research results has not been done yet to our knowledge, the case has been made against the assumption of universality for developmental research as well (Singh et al., 2021). 
Although linguistics has a long history of valuing diversity, a sampling bias has also been observed in linguistic research at large (Majid & Levinson, 2010), and specifically in publications on child language. Kidd and Garcia (2022) systematically sampled publications from child-language journals and found a bias towards specific continents (North-America and Europe) and specific languages (most work was done on English, followed by a large margin by French and Spanish). The consequences of biased sampling for studies of language acquisition and processing is only starting to be discussed (Christiansen et al., 2022).<!-- One of the contributions of this paper is to discuss how this bias may affect samples of linguistic input to children. -->
	Henrich et al.'s paper served to draw attention to the problem, but the creation of the WEIRD acronym led some to a simplistic view of comparing WEIRD and non-WEIRD populations. Particularly problematic is the impression that non-WEIRD is an internally homogeneous natural class (Ghai, 2021).<!--, despite the fact that this category contains widely diverse populations and would include both a child growing up in ultra urban and industrial Tokyo and a child growing up in a forager-horticulturalist Tsimane' village. --> Heterogeneity may be particularly marked for non-WEIRD samples: As Figure SM1 illustrates, variation in education, industrialization, wealth, inequality and fertility is greater among non-Western countries than among Western ones. <!--There is also some evidence of variability in input within putatively non-WEIRD samples: A recent analysis of several corpora found 3 times as much child-directed speech in a non-WEIRD sample, constituted of Argentinean urban infants, compared to another non-WEIRD sample, representing children growing up in a rural site; interestingly, the rural sample heard about as much child-directed speech per hour as some North-American infants (Bunce et al., 2021).-->

	Thus, generalizing from WEIRD to non-WEIRD samples is problematic, but so is generalizing from one non-WEIRD sample to another. In fact, we do not yet know which features of a culture are good predictors of a generalizability of results. The question of which dimensions in the WEIRD acronym, and related variables, we can expect to be most relevant to predict variation in children's language input is both theoretical and empirical. Thus, we start this paper by surveying each letter in the WEIRD acronym separately as a starting point. We examined its relevance to the study of child language development based on prior conceptual discussions and data reports. <!--Some of these factors are correlated, such that it is not obvious what each separate "letter" contributes (see Figures 1 and 2). --> Then we added other known relevant factors for child development.This effort led to exclude variables such as "Western" and "Democratic" (but for the curious reader, the description of these factors and their relation to language development is described in SM)
	
<!--### Western
The great majority of research on language acquisition comes from Western households. But what is “Western”? In this section, we show that the apparent categorical split actually hides a multidimensional space, and there is no consensus about which countries count as Western.
Indeed, Henrich et al. (2010), following Arnett (2008), include Australia and Israel in their definition of Western, so obviously this is not a geographical distinction. Instead of being a geographic descriptor, the West is generally considered to be a collection of cultural-religious and historical-political traditions that include, among other things, the Judeo-Christian tradition, the Greco-Roman affinity, the enlightenment ideals, the industrial revolution and democracy (Kurth, 2003). In contrast to Henrich et al.’s list just evoked, the World Atlas (Shvili, 2021) lists as Western the United States of America, Canada, Australia, New Zealand, UK, Norway, Iceland, Switzerland and the countries of the European Union; and Huntington (2000) lists a number of “torn countries”, which are hard to align with either Western or non-Western, such as Mexico, Turkey, and Russia. If we take a simplistic definition of Western as belonging to Europe and its former colonies in North America and Oceania, we might still not be satisfied, because not everyone would agree that a child growing up in the aboriginal village Alura in Australia should be considered Western. From a conceptual standpoint, the "W" is the least well-delineated of the letters making up the WEIRD acronym. Moreover, the use of Western itself might hide large differences among various non-Western (and Western) cultures, as shown in Figure 1 above.
	A short review of results in language input research does not convince us of the usefulness of the category on theoretical or empirical grounds. From a theoretical viewpoint, we have not read claims suggesting that the cultural baggage associated to Western values matters for the amount or quality of linguistic input to children either. To be certain, individuals in Western countries tend to have greater access to schooling (captured by Educated), live in cities or towns (captured by Industrialized), and have higher incomes (captured by Rich). We also believe other characteristics such as smaller family size, which are often found in Western countries (as exemplified in Figure 1), may indeed be a useful predictor for children's linguistic input. 
Western does not appear to be a useful grouping factor on empirical grounds either. For example, Fernald et al. (1989) found differences between 6 mothers and 6 fathers speaking North-American English and all other languages studied: French, Italian, German, Japanese, and even British English. North-American mothers showed a greater intonational exaggeration in infant-directed speech than all other cultural groups. In this case, Western vs. non-Western did not play a role - to the contrary - Japanese mothers produced speech that was similar to mothers from four Western cultures, while different Western cultures (North American vs. the other four) did show differences. 
In sum, given the difficulty in deciding what countries count as Western, the confounds between Western and other factors, and its apparent lack of relevance to language acquisition research on both empirical and conceptual grounds, we will not consider this factor in our analyses.-->

### Educated and Rich
Decades of research have examined differences in the quality and quantity of linguistic input among (typically Western) families who differ in their Socio-Economic Status (SES), a composite concept often based on the parents' education and income/wealth, as well as occupation. In view of this literature, we discuss Educated and Rich in a single section. 
Due to space limitations, we cannot go into detail into the theories that attempt to account for the complex causal pathways that may connect parents' education and income to children's language outcome. Given the interest in these variables found in previous language acquisition research, it may be sufficient to recommend to readers Rowe (2018) as an entry point to this literature, as well as Golinkoff et al. (2019) and Sperry et al. (2019) for divergent theoretical perspectives. 
Similarly, a large body of literature empirically documents correlations between parental SES and children's linguistic input, too large to provide a full overview here. For example, Hoff (2003b) compared the speech of high versus low SES American mothers, with SES defined based on education (college-educated versus maximally high school) and occupation (if employed, the former were in professional or managerial positions versus semi- or unskilled positions). The former group produced more utterances to their child, with more diverse vocabulary, and in slightly longer phrases, with a higher number of utterances continuing a topic the child had brought up (for comparable findings, see Hart & Risley, 1995; Hoff-Ginsberg 1990; Hoff, 2003a, 2003b; Huttenlocher, et al., 2002, 2007). It should be noted, however, that some of this literature has been found to reflect majority biases, including in what kinds of language input is "counted", and what features of linguistic experiences are valued (Sperry, et al., 2019). Nonetheless, in this paper, we do not take a stance on what characteristics of language input are desirable but rather discuss the extent to which the dimensions in the WEIRD acronym are potentially useful to predict input variation. 
To conclude this section, conceptual and empirical findings suggest that in any multi-cultural, multi-country study, it is important to take into account socio-economic status. This led us to consider education, wealth/income, and profession in our analyses. 

### Industrialized
When considering the degree of industrialization or urbanization, we are not facing a simple dimension or continuum, but a point in a multidimensional space. In our view, this letter represents the system of socioeconomic and cultural organization for a society as a whole. Whereas income can capture access to resources, which varies within a country as well as across countries, industrialization is the systemic organization at a level higher than individual families, in which case several lines of conceptual and empirical research, that we summarize next, become relevant.
Within the general theoretical framework of language socialization, there have been proposals suggesting that societies varying on the industrialized dimension also have differing views of the role of children in conversations and more generally in the community (e.g., Sharma & Levine, 1998; Richman et al., 1992; Draper & Harpending, 1987; Keller, 2012). For instance, Keller (2012) discusses three prototypical cases: urban, rural, and hybrid. These three groups differ in terms of their goals for children, with urban families aiming for child psychological independence, rural families for child physical autonomy and interdependence, and the hybrid families aiming for some mix across these values. Vogt et al. (2020) employ this conceptual classification to interpret their results on multimodal language use across three samples, namely urban Dutch, urban Mozambique, and rural Mozambique, finding that both quantity of gestures, gesture-speech alignment, and gesture types vary across the three groups in ways that can be related to Keller's typology. 
It appears likely that conceptual dimensions related to the mode of systemic organization are relevant for describing children's language input. Thus, we include rurality in our analyses below.

<!--### Democratic
The second of the WEIRD dimensions that we will argue has little to offer in the field of early language development is Democratic. To our knowledge, there is no conceptual proposal that relates democratic or autocratic modes of government with any features of early language input, nor empirical analyses suggesting differences along this dimension. We thus do not discuss it any further.-->

### Other factors: Language identity, monolingualism, and variables related to family structure
One factor not included in the WEIRD acronym but that is likely to matter for features of children's linguistic input is the language or languages that children are exposed to. A strong case has already been made in the literature for the importance of diversifying participant samples in terms of language (Kidd & Garcia, 2022), and we therefore do not dwell on it much, other than to say that this is a feature that we will report on in our analyses below. 
In addition to language identity, we will also discuss whether the families recorded are monolingual or not, and compare this against the frequency of monolingualism in the world's population. The fact of having a multilingual exposure is naturally very relevant to any analysis of both quantity and composition of the input (McCabe et al., 2013). 
Another factor not overtly included in WEIRD but which seems to be crucial based on previous findings of effects on children's language outcomes is family structure (e.g., Blake, 1981; Duncan & Paradis, 2020; Havron et al., 2022). Family structure may relate to the industrial/rurality and education dimensions discussed above, as well as to income. Industrialized societies typically have high rates of school prevalence and high levels of age-related functional specialization (e.g., Richman et al., 1998; a review in de Lancy, 2014). This results in the child spending most of their waking time with one primary caregiver who is an adult. For example, in most middle-class Euro-American families, parents are expected to have absolute responsibility over their children, which may explain why most studies focus on maternal input (e.g. Bakermans-Kranenburg et al., 2004; Huttenlocher et al., 2010; Ispa et al., 2004; Pan et al., 2005). In archetypal small-scale farming as well as foraging societies, on the other hand, it may be common that allocare is provided by older siblings (Weisner et al., 1977), and more generally older children and adolescents. According to Barry and Paxson (1971), mothers were the principal caretakers in only 57% of the 158 societies for which there was relevant information.  Drawing from varied sources, it does appear to be the case that there is considerable variability between societies in terms of how much speech is addressed to young children by other children (compare, for instance, Casillas et al., 2019; Cristia et al., 2019; Loukatou et al., 2021; Shneidman & Goldin-Meadow, 2012).
The habit of co-residing with extended family members is also a feature in certain places that are industrialized. For instance, Isleyen (2021) provides qualitative data for Turkish families choosing to buy or build an apartment so that each nuclear family lives in a different flat, but sharing common spaces and remaining very close for support, including saliently child care. In such settings, the child is surrounded by adults and children from the extended family. 
The answer to the question of who surrounds the child may also depend on how large the nuclear family is, which is related to fertility. There is considerable cross-population variation in terms of the average number of children a woman has in her reproductive lifetime, varying between a little over 1 (1.07, in Taiwan) to over 7 (7.46, in Niger). As a result, the average child will be first-born and an only child in the former case, or third-born and have 5 siblings in the latter. Differences in female fertility are due to a complex host of factors, but two dimensions that explain some variance are education and wealth: As shown in Figure 1, there is a strong negative correlation across countries, such that countries have lower fertility rates when they have greater GDP and/or where a greater proportion of the population finishes lower secondary school. This is also statistically true within many countries, with less educated and/or wealthy women having more children (e.g., Mertehikian, 2021). Some research suggests that input quantities vary as a function of the child's birth order (Bornstein et al., 2019), and it is likely that children with siblings receive at least some of their input from those siblings (Loukatou et al., 2021). 

## The current study
	We have argued that, although Western and Democratic can be safely put aside, conceptual and empirical results argue for the consideration of variation in education, wealth, and rurality present in the WEIRD acronym. In addition, we also argued for the consideration of language, monolingualism, and aspects related to family structure. 
Next, we turn to an empirical analysis of a major archive of child-centered language, the CHIld Language Data Exchange System (CHILDES, MacWhinney, 2000), where we investigate the extent to which this archive represents a biased view of children's language input, with an over-representation of monolingual, small, nuclear, urban, rich families where parents are highly educated, and with a limited representation of language variation. The CHILDES database is the major archive of freely available child-centered corpora on language acquisition. It stores data on dozens of languages as well as corpora of language acquisition in non-monolingual contexts, acquisition with clinical populations and cross-linguistic samples of spontaneous conversations, narrative data, elicitation tasks and picture descriptions. For the present paper, we focus on corpora bearing on typically-developing participants engaging in spontaneous conversations in their natural environment. 
We classified each included corpus along a number of variables related to the dimensions discussed in the Introduction (see Table 1) on two levels: the country in which the corpus was recorded (country-level analysis), and the individual families recorded (corpus-level analysis). Specifically, taking into account these dimensions, we aimed to address two descriptive research questions: (1) According to the country-level variables, to what extent do countries in CHILDES represent countries in the world? and (2) According to corpus-level variables, to what extent do CHILDES participants represent their countries population? 
# Methods
Analyses and visualizations were carried out using R (version 4.1.2, R Core Team, 2020) and ggplot2 (Wickham, 2016). The online Supplementary Materials include a document with supplementary analyses (SM1), a document with information about data entry (SM2), the analyzed dataset (SM3), and a zipped folder containing information for reproducing analyses (SM4). These materials are private and anonymized for peer review but will be rendered public upon acceptance. The link is https://osf.io/q9w82/?view_only=a013f1b25b8c4556b8248f12870402c9.
A total of 321 corpora were initially considered. We excluded 10 because at least some of the children were not typically developing; 22 because data was collected in the lab or school; 9 because data was not available; 19 because only the child was transcribed; 11 because they were diary studies; 67 because speech was triggered by a task (elicitation, story-telling, etc.); 3 because the conversation involved exclusively unfamiliar adults. After these exclusions, 180 corpora remained. 

## Country-level information
Information at the country level was gleaned from official sources. We relied on the World Development Indicators (WDI) from the World Bank, available via the WDI package in R (Vincent Arel-Bundock, 2021), for GDP and proportion of the population that lived in rural areas. We employed indicators for the year 2011, because this was the year at which we had the maximum amount of data available for those variables. For education information and fertility rate data, we turned to Our World in Data, an organization that collates information from a variety of official sources. We downloaded information on the proportion of the population that had completed lower secondary school (data from 2007-2015; Our World in Data, 2022a), as well as fertility rate (data corresponding to 2011; Our World in Data, 2022b). Definitions for these variables are provided in Table 2.

## Corpus-level information
A team member attempted to fill in information for each corpus under 35 different categories (see SM2 for the full list) deemed to potentially encompass different aspects of population variation prior to the conceptual work laid out in the Introduction. To fill in the information for each category per corpus, the annotator looked into the description provided by the CHILDES page of the corpus; they then looked up every reference if accessible (articles, book chapters or dissertations) indexed in that same page; and spot-inspected associated transcripts. All missing variables were entered as NA (not available). 
Realizing some variables were entered too rarely to be of any utility, we reduced the number of fields to 22. We then attempted to contact the corresponding authors associated with each corpus with a request for additional information that was missing or incomplete from our initial screening, or which could be improved based on their personal notes and experience from collecting the corpus (e.g., how many siblings the recorded child had). We attempted to contact all corpus curators, and not just curators of the 180 included corpora. Out of the 321 corpora in CHILDES, we could not find an email address for any of the corpora curators for 24 of the corpora, and for 14 more we found an email address but it did not seem to be functional; 12 additional corpora had curators who had passed away. We sent each author access to an online table, indicating which rows corresponded to their corpus, plus definitions of each of the variables to be entered. We were overwhelmed by the curators' positive responses: Over a third of the curators contacted replied, and 98% of them were able and willing to provide us with additional data and/or confirmed that the information was indeed missing. 
Finally, we further whittled down variables to those that were reported sufficiently frequently and seemed most relevant to our study. The precise definitions are provided in Table 3.

# Results
The samples are varied in geographic terms, with corpora for every populated continent. Specifically, 3 corpora were collected in Africa; 32 in Asia; 73 in Western Europe, and a further 32 in Non-Western Europe; 34 in North America and 73 in Latin America. Only 1 was collected in Oceania.


## Country-level variables
Using country-level statistics, we were able to assess the extent to which the countries with data in CHILDES were a representative sample of countries in the world. Density plots are portrayed in Figure 3. The means for each of the variables differed for the countries in CHILDES versus overall in the world using unpaired samples t-tests without assuming equality of variance (Welch's t). Countries in CHILDES had a higher proportion of the population completing lower secondary school than the world wide sample (% compl. LSS, t(101.59) = 5.79, p < .001); they were more urban (% urban, t(79.77) = 3.51,  p < .001); richer (log GDP per capita, t(103.29) = 6,  p < .001) and had lower fertility rates (log fertility, t(117.09) = -6.85, p  p < .001).


## Corpus-level variables
We then investigated the extent to which samples themselves captured diverse families starting with our selected variables related to the WEIRD acronym, before turning to the other factors of relevance we argued for in the Introduction. 
Education information was missing for more than half of the corpora (see Table 3); and 4 were described as diverse, without clarifying the range of education covered. Of the remaining 76 samples, 3 had at least some parents with primary-level education; 9 had parents with secondary school education as the lower bound of the education range, and a further 6 had some college as the lower bound. Thus, 76% of the samples (N = 58) portrayed children whose parents had at least a graduate, if not a postgraduate, degree. Samples were not representative of the countries they were collected, since in those same countries the proportion of the population with tertiary education was only 16%.
For socioeconomic status, there were 78 missing values (43%). Of the remaining 102 samples, 5 were described as having low SES; 16 were described as spanning both lower and middle or higher SES; and 81 were described as middle or higher SES exclusively. Given that most countries represented in CHILDES are in the Organization for Economic Cooperation and Development (OECD, 150 out of the 180 corpora), we can compare this proportion with the proportion of the population in these countries that are middle class. According to a 2016 report, “Almost two-thirds of people live in middle-income households in OECD countries”, for whom “household net income [is] between 0.75 and 2 times the median”. Thus, middle and higher class participants appear to be over-represented in CHILDES data, composing 81% of available data.
Information about parents’ profession or activity was also missing for the majority of the corpora (see Table 3). Professions were overall varied, but it should be noted that 50% of the samples contained parents who were described as (Masters or PhD) students, professors, linguists, researchers, scientists, or academics. To give an idea of the extent to which this is not representative, consider the fact that in 2020, 6% of the American population would be included in that list of professions. Similar data is hard to find for all countries represented in CHILDES, but we suspect that the proportion of scientists, professors, Masters and PhD students found in most other countries will be the same or lower.
Only about a third of the samples had information about whether the community was rural or urban (see Table 3), and the remaining ones were very homogeneous. Setting aside 115 missing values (64%), and focusing on the remaining 65 samples, 58 were described as industrialized or urban, and an additional one as both rural and urban. Only 7 samples were described as farming or rural. In these same countries, the proportion of the population residing in urban settings was 76%, suggesting that samples were not representative of their countries in terms of rural versus urban settings either.


We then turned to the additional factors, starting with how varied language backgrounds were. A total of 62 different languages or language combinations (for bilingual and multilingual children) were reportedly spoken in the corpora. The samples in which only one language was reported spoke Afrikaans, Arabic (Egyptian or Kuwaiti), Basque, Cantonese, Catalan, Cree, Croatian, Czech, Danish, Dutch, English, Estonian, Farsi, French, German, Greek, Hebrew, Hungarian, Icelandic, Indonesian, Irish, Italian, Jamaican, Japanese, Korean, Mandarin, Norwegian, Nungon, Polish, Portuguese (Brazilian or European), Romanian, Russian, Serbian, Sesotho, Slovenian, Spanish, Swedish, Taiwanese, Tamil, Thai, Turkish, Welsh, and the samples in which multiple languages were reported spoke Catalan/Spanish, Dutch/English, Dutch/French, Dutch/Italian, English/Cantonese, English/Dutch, English/French, English/Hebrew, English/Japanese, English/Japanese/Danish, English/Mandarin, English/Mandarin/Cantonese, English/Russian, English/Spanish, French/Russian, German/Spanish, Hungarian/Catalan/Spanish, Hungarian/Farsi/English, Italian/German, Italian/Japanese, Portuguese/Swedish/English, Spanish/Catalan, Spanish/English, Spanish/Galician.
About a third (32%) of the included corpora that had available data for this variable (N = 110) were not monolingual. It is hard to find reliable estimates of the percentage of the population who are not monolingual in the world or in the countries represented in CHILDES, but for instance, in Europe in 2016, 65% of adults reported knowing multiple languages (Eurostat, 2022). According to such estimates, even if samples are linguistically diverse, it would appear that input data in CHILDES under-represents bilinguals and multilinguals.
As for family structure, 60 corpora (88% of those that had data for this variable) were based on nuclear families; in 7 extended families were portrayed; and in 1 one sample the structure was varied. We do not know of a country-level index that would allow us to check whether CHILDES corpora are representative of their countries for this variable.
A majority of corpora in CHILDES include children who have siblings. In fact, only 28% of samples (among the 93 corpora having information on siblings) were constituted exclusively by children with no siblings, and the remaining had at least one sibling, with the overall average being 0.8 siblings. Since 83% of countries in CHILDES are in the OECD, we draw a comparison point for such countries: 46% of children had no siblings in OECD countries according to 2015 data. In this sense, children with no siblings appear to be under-represented in CHILDES.

# Discussion
In the current paper, we presented different dimensions of variation across populations, and then concentrated on those claimed to be important for behavioral sciences and likely relevant in predicting variation in children’s language input. We then asked how the most prominent archive of child language and child-language input used by scientists today, CHILDES, represents these relevant dimensions. Specifically, we attempted to annotate CHILDES corpora for variables representing to what extent the country-level and corpus-level variation represents the Educated, Industrialized, and Rich dimensions highlighted in previous work (Heinrich, 2010), as well as other factors we also argued should be considered: language, monolingualism, and factors related to family structure (nuclear versus extended, and fertility). 
Both in terms of our country-level and corpus-level analyses, CHILDES was biased along most of those dimensions. At the country level, , CHILDES currently over-represents countries with relatively educated populations, living mostly in urban settings, with a relatively high per capita income, and where women have relatively fewer children. 
At the corpus level, bias is particularly stark for education, with a shocking 78% of samples issuing from families whose parents had at least a college education, whereas in those same countries, individuals with at least a college education constituted a mere 15% of the population. 
Another striking result went beyond the over-representation of highly educated parents in CHILDES, and related to the likely fact that many corpora have been constituted by academics studying their own (grand)children, as shown by the analysis suggesting that nearly half of the corpora had parents with research-related professions. The danger of extrapolating from such a sample goes beyond issues previously discussed in the context of convenient (homogeneous or heterogeneous) samples (Bornstein et al., 2013), and may concern the very fact that parents who pursue a career in academia (and likely in language related areas at that) are likely unusual in their verbal habits.
At the corpus level, CHILDES also contains a large majority of data from urban communities, and nuclear families, which, based on literature summarized in the Introduction, will tend to have an over-representation of speech from mothers, despite the fact that modes of caregiving centered exclusively around the mother are a statistical minority according to at least one anthropological report (Barry & Paxson, 1971). 
Regarding the additional factors we had suggested, CHILDES appears more balanced. To begin with, in CHILDES, only 11 out of 180 corpora are from North America, and thus English does not appear over-represented in terms of number of corpora (but see Christiansen et al., 2022, for evidence that it may be in terms of overall quantity of data). Additionally, there is a fair representation of multi-child families: only 24% of samples for which we have data on siblings recorded only-children. That said, the fact that included children had siblings does not, per se, mean that siblings' speech will be represented in the transcribed corpus. Our own impression of working with some of the corpora is that recordings were sometimes scheduled so as to exclude the sibling, or even if the sibling was present, their speech may not be as often transcribed as that of other partners (Loukatou et al., 2021, p. 16). 
Our analyses focused on description of samples along each of the dimensions, but readers may wonder, how well-represented are combinations of values along those dimensions? Given that most samples are nuclear families with well-educated parents living in urban sites, it will be impossible to tease apart these three dimensions, which are in effect confounded in CHILDES corpora (and in the world, see Figure 2). Even in a case where we do have some variation, namely the presence of siblings, it will be hard to understand the intersectionality of such effects. Table 4 exemplifies this: It may be reasonable to compare the input afforded to children who have at least one sibling (1+) versus none for samples consisting of parents with a completed college education, but families with lower levels of education are too under-represented to allow a meaningful study. 

## Future directions
	Through these analyses, we were able to provide a survey of three dimensions routinely included in the discussions about WEIRD sampling (namely education, industrialization, and income), as well as other dimensions that we argued in the Introduction should also be considered when studying child-language acquisition (language, monolingualism, and factors related to family structure). Our arguments in the Introduction were based on conceptual frameworks and empirical results suggesting each of these dimensions should predict input quantity and composition. However, low variability and the rarity of certain combinations will make it hard for work on CHILDES to assess whether input quantity and composition vary as expected given those same conceptual frameworks and results previously observed in smaller datasets. 
How can the field of early language acquisition achieve a more representative view on children's linguistic input? We can see a few strategies that individuals and the field can take.  Regarding individual researchers, many will be based in countries that have considerable levels of socioeconomic inequality or varied family structure, and by making an additional effort, they could recruit from more varied households (see Christiansen et al., 2022). For example, in Israel, the average non-religious family has 2.08 children, whereas the average ultra-orthodox family has 6.56, with other religious groups having intermediate family sizes (Israeli Central Bureau of Statistics,  2020). In this case, it will be important to follow advice on the possibility of not attempting to recruit a truly representative sample, but instead recruiting a structured sample with many participants from each of the backgrounds ("homogeneous" sampling). As cogently explained by Bornstein et al. (2013), there are several advantages of the latter strategy in terms of both clarity and the extent of generalizability, as well as the fact that recruitment efforts can focus on a subset of the population. It will be important to be careful about how such subsets of the population are portrayed (see Talbert, 2019, for ethics of working with minorities; and Gehlert & Mozersky, 2018 for participatory research guidelines).
	As a field, we might need to take a leaf from business textbooks and ask ourselves what are the "key performance indicators" for diversity we should be tracking and optimizing for, since this can also help us focus our efforts in increasing diversity along the dimensions we believe are most crucial (as argued in Havron et al., 2022). For instance, if we want many languages and countries represented, it is likely that we can continue as usual, since students and researchers of many countries may continue recording their interactions with their own children, and contributing those data to CHILDES. However, we need to be careful about falling back onto this status quo, as the proportion of authors contributing to language acquisition literature is tremendously biased according to Kidd and Garcia (2022), with 87% of papers being published by North Americans or Europeans authors, and a further 4% from Australia and New Zealand. The remaining 9% mainly came from East or West Asian authors, with 1% for all other regions combined.
Additionally, the small proportion of international authors that do contribute to CHILDES will themselves not be randomly sampled from their country's population: They are likely to be highly educated. Thus, if we believe that socioeconomic variation is a relevant predictor of children's input, then we need to find creative ways to support individuals from lower socioeconomic strata to similarly document their own children's input, including engaging in partnerships with more varied communities than we do at present. It is possible that researchers actually have such data that could be shared, but have been unable to take the steps required to get the dataset in a CHILDES-compatible format. Grants that pay for experts taking on these transformations, and/or that fund students of those researchers to take this on, may help solve this issue.
As for metrics to track and optimize for, a simple metric we could incorporate to assess diversity in CHILDES is caregiver education level. This is a bit of data that can already be incorporated in the CHILDES' native metadata, and could therefore be extracted automatically. Since most corpora did not supply information on many of the dimensions we analyzed, neither in the description of the corpus nor in the referenced papers, we contacted creators of CHILDES corpora whenever possible, and asked them to complete or correct the information we found. Despite this large-scale effort and the collaboration of over one hundred corpus curators, many variables of interest were still missing (see Table 2). One take home message from this endeavor is therefore our suggestion to authors to supply as much information as possible with their corpora in the future, especially at the level of individual families recorded. For example, information about education is not particularly sensitive and does not require extra information to interpret, unlike occupation and income (for whose interpretation one needs to know at least the year of data collection and distribution of income in the country). Also, information about the geographic location could help assess the extent to which localities where education is widespread are over-represented; and the extent to which unusually well-educated parents are over-represented. These ideas are relevant to any archive (including but not limited to CHILDES and Databrary, Gilmore et al., 2016). We provide recommendations specific to CHILDES in the Supplementary Materials (SM1).
From a theoretical viewpoint, however, education and geographic location is not sufficient. As argued in the Introduction, both theoretical proposals and empirical results suggest that rurality (or more broadly, the socio-economic structure of a local society), income, fertility, and family structure all likely contribute to variation in quantitative and qualitative aspects of children's linguistic input. Tracking these other dimensions does not seem overly costly or problematic, in our view. With the possible exception of income, the other metrics will be either obvious (whether the family is in a city or not) or not particularly sensitive (who else lives in the same household). 
# Conclusion
CHILDES is, undoubtedly, the leading archive of child-centered recordings, and an example of the value of cumulative science more broadly. Having argued for the usefulness of dimensions like education and industrialization as potential factors predicting variation in children's language input, we went on to check how varied CHILDES corpora were along those dimensions. We found that data from many countries and languages exist in this priceless resource, but that these countries did not constitute a representative sample of the world's countries, and furthermore that families could not be viewed as representative of these countries. We also noted low variability along certain dimensions (saliently family structure) and general confounds across dimensions of variation. Our discussion led us to argue for the systematic inclusion of certain descriptors in speaker-level and corpus-level metadata, in order to track and quantify both diversity and representativity. 


